FileVersion = 1

[Project]
Name = "amoeba-beef"
DefaultNamespace = "amoeba"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\amoeba_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\amoeba.lib"]
