FileVersion = 1

[Project]
Name = "amoeba-beef"
DefaultNamespace = "amoeba"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\amoeba.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\amoeba.lib"]
