FileVersion = 1

[Project]
Name = "amoeba-beef"
DefaultNamespace = "amoeba"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\amoebad.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\amoeba.lib"]
